<?php
/*------------------------------------------------------------------------
 # SM Listing Tabs - Version 2.2.1
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
use Magento\Framework\App\Action\Action; 
$helper = $this->_helper();
if ($this->_isAjax()) {
    $type_filter = $this->_getConfig('product_source');
    switch ($type_filter) {
        case 'categories':
            $catid = $this->getRequest()->getPost('categoryid');
            $child_items = $this->_getProductInfor($catid);
            break;
        case 'fieldproducts':
            $field_order = $this->getRequest()->getPost('categoryid');
            $catid = $this->_getCatIds();
            $child_items = $this->_getProductInfor($catid, $field_order);
            break;
    }
}
if (!empty($child_items)) {
    $j = $this->getRequest()->getPost('ajax_listingtabs_start', 0);
	$nb_type_show = $this->_getConfig('show_loadmore_slider');
	$nb_rows = $this->_getConfig('nb_rows', 1);
	$i = 0;
	$count = count($child_items);
    foreach ($child_items as $_product) {
        $i++;$j++; ?>
        <?php if($nb_type_show == 'slider' && ($i % $nb_rows == 1 || $nb_rows == 1)) { ?>
			<div class="ltabs-item item">
		<?php } ?>
		<?php if ($nb_type_show == 'loadmore'){ ?>
        <div class="ltabs-item new-ltabs-item">
		<?php } ?>
            <div class="item-inner">
            <?php if (($this->_getConfig('show_theme') == 'deals') && ($this->_getConfig('product_countdown_display') == 1)) {
	            $specialPriceToDate = $_product->special_to_date;
	            ?>
	            <div class="ltabs-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialPriceToDate)); ?>"></div>
            <?php } ?>
				<?php if ($_product->_image && $this->_getConfig('product_image_display')) { ?>
				
                <div class="box-image">
					<a href="<?php echo $_product->link ?>"
					   title="<?php echo $_product->title; ?>"
						<?php echo $helper->parseTarget($this->_getConfig('target')); ?>
						>
						<img src="<?php echo $_product->_image; ?>"
							 title="<?php echo $_product->title; ?>"
							 alt="<?php echo $_product->title; ?>" >
					</a>

                    <!--LABEL PRODUCT-->

                    <?php
                    $specialprice = $_product->getSpecialPrice();
                    $specialPriceFromDate = $_product->getSpecialFromDate();
                    $specialPriceToDate = $_product->getSpecialToDate();

                    $today = time();

                    if ($specialprice) {
                        if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                            <div class="label-product label-sale">
											<span class="sale-product-icon">
												<?php echo __('Sale'); ?>
											</span>
                            </div>
                        <?php }
                    }
                    ?>

                    <?php
                    $now = date("Y-m-d");
                    $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                    $newsTo = substr($_product->getNewsToDate(), 0, 10);

                    if ($newsTo != '' || $newsFrom != '') {
                        if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
                            <div class="label-product label-new">
                                <span class="new-product-icon"><?php echo __('New'); ?></span>
                            </div>
                        <?php }
                    } ?>

                    <!--END LABEL PRODUCT-->

                    <?php if ((int)$this->_getConfig('product_addcart_display', 1) ||(int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
                        <div class="bottom-action">
                            <a style="display: none;" href="<?php echo $_product->link;?>">&nbsp;</a>
							
								<?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
									<?php if ($_product->isSaleable()){ ?>
										<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)){ ?>
											<button class="btn-action btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}' type="button" data-toggle="tooltip" data-placement="left" title="<?php  echo __('Add to Cart') ?>">
												<span><?php  echo __('Add to Cart') ?></span>
											</button>
										<?php } else { ?>
											<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
											$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
											?>
											<button class="btn-action btn-cart"
													data-post='<?php echo $postData; ?>'
													data-toggle="tooltip" data-placement="left" 
													type="button" title="<?php  echo __('Add to Cart') ?>">
												<span><?php echo __('Add to Cart') ?></span>
											</button>
										<?php } ?>
									<?php } else { ?>
										<?php if ($_product->getIsSalable()){ ?>
											<div class="stock available"><span><?php  echo __('In stock') ?></span></div>
										<?php } else { ?>
											<div class="stock unavailable"><span><?php  echo __('Out of stock') ?></span></div>
										<?php } ?>
									<?php } ?>
								<?php } ?>

								<?php if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1) ){ ?>
										<a href="#" data-post='<?php  echo $block->getAddToWishlistParams($_product); ?>'  class="btn-action link-wishlist towishlist" data-action="add-to-wishlist" data-toggle="tooltip" data-placement="left" title="<?php  echo __('Add to Wish List') ?>">
											<span><?php  echo __('Add to Wish List') ?></span>
										</a>
									<?php } ?>
									<?php if ($block->getAddToCompareUrl() &&  (int)$this->_getConfig('product_addcompare_display', 1)){ ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<a href="#" class="btn-action link-compare tocompare"
										   data-post='<?php  echo $compareHelper->getPostDataParams($_product);?>'
										   data-role="add-to-links"
										   data-toggle="tooltip" data-placement="left" 
										   title="<?php  echo __('Add to Compare'); ?>">
											<span><?php  echo __('Add to Compare') ?></span>
										</a>
									<?php }; ?>
								<?php } ?>							
                        </div>
                    <?php } ?>	<!--END ACTION-->

                </div>		

				<?php }?>

				<!-- Begin spc-content -->

				<div class="box-info">
					<?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
						<div class="rating-box">
							<?php
							$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
							echo $block->getReviewsSummaryHtml($_product,$templateType);
							?>
						</div>
					<?php } ?>

					<?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
						<h2 class="product-name">
							<a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
								<?php echo $helper->parseTarget($this->_getConfig('target')); ?>
								>
								<?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
							</a>
						</h2>
					<?php } ?>

					<?php if ($this->_getConfig('product_description_display') == 1 && $helper->_trimEncode($_product->_description)) { ?>
						<div class="bs-description">
							<?php echo $_product->_description; ?>
						</div>
					<?php } ?>
					
					<?php if ($this->_getConfig('cat_title_display') == 1 && $this->_getConfig('product_source') != 'media') { ?>
						<div class="bs-category"><?php echo __('Category:&nbsp') ;?>
							<a  href="<?php echo $_product->cat_link; ?>"  title="<?php echo $_product->cat_title; ?>"  <?php echo $helper->parseTarget($this->_getConfig('target')); ?>>
								<?php echo  $helper->truncate($_product->cat_title, $this->_getConfig('category_title_max_characs', 25)); ?>
							</a>

						</div>
					<?php } ?>

					<?php if ($this->_getConfig('product_source') != 'media') { ?>


						<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
							<div class="price-box">
								<div class="sale-price">
									<?php echo $this->getProductPrice($_product); ?>
								</div>
							</div>
						<?php } ?>

					<?php } ?>

					<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
						<div class="bs-detail">
							<a href="<?php echo $_product->link ?>"
							   title="<?php echo $_product->title; ?>"
								<?php echo $helper->parseTarget($this->_getConfig('target')); ?>
								>
								<?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
							</a>
						</div>
					<?php } ?>
				</div>
						
        </div>
		<?php if($nb_type_show == 'slider' && ($i % $nb_rows == 0 || $i == $count)) { ?>
		</div>
		<?php }
		if ($nb_type_show == 'loadmore'){ ?>
			</div>
		<?php } ?>
        <?php $clear = 'clr1';
        if ($j % 2 == 0) $clear .= ' clr2';
        if ($j % 3 == 0) $clear .= ' clr3';
        if ($j % 4 == 0) $clear .= ' clr4';
        if ($j % 5 == 0) $clear .= ' clr5';
        if ($j % 6 == 0) $clear .= ' clr6';
        ?>
        <?php if( $this->_getConfig('show_loadmore_slider') == 'loadmore'){ ?>
            <div class="<?php echo $clear; ?>"></div>
        <?php } ?>
    <?php
    }
}?>