<?php
	$_config = $this->helper('Sm\Maxshop\Helper\Data');
	$footerStyle = $_config->getGeneral('footer_style');

	include (dirname(__FILE__).'/footer/'.$footerStyle.'.phtml');

?>

<?php if($_config->getAdvanced('show_gototop')){ ?>
    <a id="yt-totop" href="javascript:void(0)" title="Go to Top"></a>
    <script type="text/javascript">
        jQuery(document).ready(function($){
            $("#yt-totop").hide();
            $(function () {
                var wh = $(window).height();
                var whtml =  $(document).height();
                $(window).scroll(function () {
                    if ($(this).scrollTop() > whtml/10) {
                        $('#yt-totop').fadeIn();
                    } else {
                        $('#yt-totop').fadeOut();
                    }
                });
                $('#yt-totop').click(function () {
                    $('body,html').animate({
                        scrollTop: 0
                    }, 800);
                    return false;
                });
            });
        });
    </script>
	
<?php } ?>

<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
echo $objectManager->get('Magento\Framework\View\LayoutInterface')->createBlock('Magento\Customer\Block\Form\Login')->setTemplate('Magento_Customer::form/mini.login.phtml')->toHtml();
            ?>		
        
